[pytest]
filterwarnings =
    ignore::DeprecationWarning:netCDF4.*
    ignore:Setting the shape on a NumPy array:DeprecationWarning
    ignore::Warning:fastapi.testclient
    ignore::Warning:starlette.testclient
    ignore:.*BlockingPortal.*:DeprecationWarning
